#!/bin/sh
SYNOPKG_PKGNAME="rathole"
SYNOPKG_PKGDEST="/var/packages/${SYNOPKG_PKGNAME}/target"

# Stop service before uninstall
if [ -x "${SYNOPKG_PKGDEST}/scripts/start-stop-status" ]; then
    "${SYNOPKG_PKGDEST}/scripts/start-stop-status" stop
elif [ -x "/var/packages/${SYNOPKG_PKGNAME}/scripts/start-stop-status" ]; then
    "/var/packages/${SYNOPKG_PKGNAME}/scripts/start-stop-status" stop
fi

exit 0
